PARTICLE_SHAPE = (9,)

NEUTRON_RESPONSE_SHAPE = (44, 44, 1)
PROTON_RESPONSE_SHAPE = (56, 30, 1)
RESPONSE_SHAPE = PROTON_RESPONSE_SHAPE

LATENT_NEUTRON_RESPONSE_SHAPE = (11, 11, 4)
PROTON_LATENT_RESPONSE_SHAPE = (14, 8, 4)
LATENT_RESPONSE_SHAPE = PROTON_LATENT_RESPONSE_SHAPE
