from enum import Enum


class ParticleType(Enum):
    NEUTRON = 0
    PROTON = 1


PARTICLE_TYPE = ParticleType.PROTON
PARTICLE_SHAPE = (9,)

NEUTRON_RESPONSE_SHAPE = (44, 44, 1)
PROTON_RESPONSE_SHAPE = (56, 30, 1)

NEUTRON_LATENT_SHAPE = (11, 11, 4)
PROTON_LATENT_SHAPE = (14, 8, 4)

if PARTICLE_TYPE == ParticleType.NEUTRON:
    RESPONSE_SHAPE = NEUTRON_RESPONSE_SHAPE
    LATENT_SHAPE = NEUTRON_LATENT_SHAPE
elif PARTICLE_TYPE == ParticleType.PROTON:
    RESPONSE_SHAPE = PROTON_RESPONSE_SHAPE
    LATENT_SHAPE = PROTON_LATENT_SHAPE
